# Generated by Django 4.2.7 on 2025-04-15 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassInformation",
            fields=[
                (
                    "ClassID",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="班级编号",
                    ),
                ),
                (
                    "ClassName",
                    models.CharField(max_length=100, verbose_name="班级名称"),
                ),
                ("Grade", models.CharField(max_length=50, verbose_name="年级")),
                (
                    "ClassAdviser",
                    models.CharField(max_length=100, verbose_name="班主任"),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "班级信息",
                "verbose_name_plural": "班级信息",
                "ordering": ["-CreatedAt"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "CourseID",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程编号",
                    ),
                ),
                (
                    "CourseName",
                    models.CharField(max_length=100, verbose_name="课程名称"),
                ),
                ("CourseDescription", models.TextField(verbose_name="课程描述")),
                (
                    "Credits",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="学分",
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程信息",
                "verbose_name_plural": "课程信息",
                "ordering": ["CourseName"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "StudentID",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学号",
                    ),
                ),
                ("Name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "Gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "Age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="年龄",
                    ),
                ),
                ("EnrollmentDate", models.DateField(verbose_name="入学日期")),
                (
                    "Phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="电子邮箱"
                    ),
                ),
                (
                    "Address",
                    models.TextField(blank=True, null=True, verbose_name="家庭住址"),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "Class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.classinformation",
                        verbose_name="班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生信息",
                "verbose_name_plural": "学生信息",
                "ordering": ["-CreatedAt"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "ScoreID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="成绩编号"
                    ),
                ),
                (
                    "RegularGrade",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="平时成绩",
                    ),
                ),
                (
                    "MidtermGrade",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="期中成绩",
                    ),
                ),
                (
                    "FinalGrade",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="期末成绩",
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "Student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩信息",
                "verbose_name_plural": "成绩信息",
                "ordering": ["-CreatedAt"],
                "unique_together": {("Student", "Course")},
            },
        ),
    ]
